### ISSUE TITLE
Error after following readme

### ISSUE THREAD

**Issue by debonair** [ylankgz/shlack#2]
after pasting the dev.config secrets I get 

*\* (Mix.Config.LoadError) could not load config config/dev.secret.exs
    *\* (Code.LoadError) could not load /home/duma/Projects/shlack/config/dev.secret.exs
    (elixir) lib/code.ex:662: Code.find_file/2
    (elixir) lib/code.ex:295: Code.eval_file/2
    (mix) lib/mix/config.ex:150: Mix.Config.read!/1
    (mix) lib/mix/config.ex:182: anonymous fn/2 in Mix.Config.read_wildcard!/1
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5

**Comment by debonair** [comment]
never mind i misnamed the file
